In [23]:
import numpy as np
x = [1., 2., 3., 4.]
print("Original array:")
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))

Original array:
[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[0. 1. 2. 2.]


In [19]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
print("Division of the array inputs, element-wise:")
print(np.true_divide(x, 3))

Original array:
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [27]:
np.array(x)//1.5

array([0., 1., 2., 2.])

In [20]:
print(np.divide(x, 3))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [21]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [22]:
x//3

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3])

In [28]:
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))

Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


In [29]:
import numpy as np
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print("Original array:")
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceil values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))

Original array:
[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]
Floor values of the above array elements:
[-2. -2. -1.  0.  1.  1.  2.]
Ceil values of the above array elements:
[-1. -1. -0.  1.  2.  2.  2.]
Truncated values of the above array elements:
[-1. -1. -0.  0.  1.  1.  2.]


In [32]:
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.08003439 0.17913131 0.56276745]
 [0.78699129 0.55486059 0.3238707 ]
 [0.65761415 0.29238871 0.27595158]
 [0.19120755 0.09634285 0.72592633]
 [0.62746164 0.49386464 0.05259654]]
Second array:
[[0.98796558 0.48047219]
 [0.91338969 0.02677525]
 [0.74890643 0.24072329]]
Dot product of two arrays:
[[0.66414808 0.17872182]
 [1.5268731  0.47094718]
 [1.12342688 0.39022206]
 [0.82055594 0.26919688]
 [1.11039126 0.32736243]]


In [40]:
a=np.array([[4,3],[5,6]])
b=np.array([[10,11],[12,13]])
print("a")
print(a)
print("b")
print(b)
c=np.vdot(a,b)
print("c")
print(c)



a
[[4 3]
 [5 6]]
b
[[10 11]
 [12 13]]
c
211


In [34]:
import numpy as np
x = np.array([1, 4, 0], float)
y = np.array([2, 2, 1], float)
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Inner product of x and y:")
print(np.inner(x, y))
print("Outer product of x and y:")
print(np.outer(x, y))
print("Cross product of x and y:")
print(np.cross(x, y))

Matrices and vectors.
x:
[1. 4. 0.]
y:
[2. 2. 1.]
Inner product of x and y:
10.0
Outer product of x and y:
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
Cross product of x and y:
[ 4. -1. -6.]


In [35]:
import numpy as np
x = [[1, 0], [1, 1]]
y = [[3, 1], [2, 2]]
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Matrix product of above two arrays:")
print(np.matmul(x, y))

Matrices and vectors.
x:
[[1, 0], [1, 1]]
y:
[[3, 1], [2, 2]]
Matrix product of above two arrays:
[[3 1]
 [5 3]]


In [36]:
from numpy.polynomial import polynomial as P
x = (10,20,30)
y = (30,40,50)
print("Add one polynomial to another:")
print(P.polyadd(x,y))
print("Subtract one polynomial from another:")
print(P.polysub(x,y))
print("Multiply one polynomial by another:")
print(P.polymul(x,y))
print("Divide one polynomial by another:")
print(P.polydiv(x,y))

Add one polynomial to another:
[40. 60. 80.]
Subtract one polynomial from another:
[-20. -20. -20.]
Multiply one polynomial by another:
[ 300. 1000. 2200. 2200. 1500.]
Divide one polynomial by another:
(array([0.6]), array([-8., -4.]))


In [37]:
import numpy as np
x = np.array([[10, 30], [20, 60]])
print("Original array:")
print(x)
print("Mean of each column:")
print(x.mean(axis=0))
print("Mean of each row:")
print(x.mean(axis=1))

Original array:
[[10 30]
 [20 60]]
Mean of each column:
[15. 45.]
Mean of each row:
[20. 40.]


In [38]:
import numpy as np
x = np.array([1, 3, 5, 7, 0])
print("Original array: ")
print(x)
print("Difference between neighboring elements, element-wise of the said array.")
print(np.diff(x))  # subtract from the next number

Original array: 
[1 3 5 7 0]
Difference between neighboring elements, element-wise of the said array.
[ 2  2  2 -7]


In [41]:
import numpy as np
x = np.array([1., 2., 3., 4.], np.float32)
print("Original array: ")
print(x)
print("\ne^x, element-wise of the said:")
r = np.exp(x)
print(r)

Original array: 
[1. 2. 3. 4.]

e^x, element-wise of the said:
[ 2.718282   7.3890557 20.085537  54.59815  ]


In [42]:
2**x

array([ 2.,  4.,  8., 16.], dtype=float32)

In [43]:
-x

array([-1., -2., -3., -4.], dtype=float32)

In [44]:
np.negative(x)

array([-1., -2., -3., -4.], dtype=float32)