In [11]:
import numpy as np
arr=np.random.randn(5,2)

In [12]:
first,second,third=np.split(arr,[1,3])

In [13]:
first

array([[ 0.83771953, -0.31212898]])

In [14]:
second

array([[-0.89798592,  0.01764049],
       [ 0.9081316 , -0.80843507]])

In [15]:
third

array([[ 1.1312557 ,  0.18039268],
       [-0.90784035,  1.16796451]])

In [16]:
arr=np.arange(3)

In [17]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [18]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [19]:
arr=np.random.randn(2,2)

In [20]:
arr

array([[-0.85650062,  0.45611645],
       [-1.98817182, -0.352389  ]])

In [21]:
arr.repeat(2)

array([-0.85650062, -0.85650062,  0.45611645,  0.45611645, -1.98817182,
       -1.98817182, -0.352389  , -0.352389  ])

In [22]:
arr.repeat(2,axis=0)

array([[-0.85650062,  0.45611645],
       [-0.85650062,  0.45611645],
       [-1.98817182, -0.352389  ],
       [-1.98817182, -0.352389  ]])

In [23]:
arr.repeat(2,axis=1)

array([[-0.85650062, -0.85650062,  0.45611645,  0.45611645],
       [-1.98817182, -1.98817182, -0.352389  , -0.352389  ]])

In [24]:
np.tile(arr,2)

array([[-0.85650062,  0.45611645, -0.85650062,  0.45611645],
       [-1.98817182, -0.352389  , -1.98817182, -0.352389  ]])

In [25]:
np.tile(arr,(3,2))

array([[-0.85650062,  0.45611645, -0.85650062,  0.45611645],
       [-1.98817182, -0.352389  , -1.98817182, -0.352389  ],
       [-0.85650062,  0.45611645, -0.85650062,  0.45611645],
       [-1.98817182, -0.352389  , -1.98817182, -0.352389  ],
       [-0.85650062,  0.45611645, -0.85650062,  0.45611645],
       [-1.98817182, -0.352389  , -1.98817182, -0.352389  ]])